#!/bin/sh
# Clone from github
mkdir -p $HOME/.cfg

echo ".cfg" >> $HOME/.gitignore
echo "setup_script.sh" >> $HOME/.gitignore

git clone --bare https://github.com/matejciglenecki/dotfiles $HOME/.cfg

/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME checkout

# Make all dirs for conflicted files
mkdir -p .config-backup

/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME checkout 2>&1 | egrep "^\s+" | awk {'print $1'} | xargs dirname | sort -u | xargs -I{} mkdir {} $HOME/.config-backup/{}

/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} mv -p {} .config-backup/{}

/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME checkout

/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME config --local status.showUntrackedFiles no
