#!/bin/sh
sxhkd &
yakuake &

#$BROWSERUSER $BROWSERASAPP$CAL &
#$BROWSERUSER $BROWSERASAPP$TODO_TODAY &
#$BROWSERUSER $BROWSERASAPP$POMODORO &
# barrier &
trickle -s -u 6250 -d 6250 insync start &
thunderbird &
# qbittorrent &
syncthing -no-browser &
