#!/bin/sh
sxhkd &
yakuake &

$BROWSERUSER $BROWSERASAPP$CAL &
$BROWSERUSER $BROWSERASAPP$TODO_TODAY &
$BROWSERUSER $BROWSERASAPP$POMODORO &
# barrier &
trickle -s -u 70 -d 300 insync start &
thunderbird &
qbittorrent &
