#!/bin/sh
# chmod +x setup_script.sh
# ./setup_script.sh

sudo echo "Script now has sudo permissions"
rm -rf $HOME/Documents $HOME/Music $HOME/Pictures $HOME/Public $HOME/Templates $HOME/Videos
mkdir -p tmp

sudo apt update && sudo apt -y upgrade
sudo apt autoremove && sudo apt autoclean

# Install from package list, loop skips unlocated packages
for i in $(grep -vE "^\s*#" $HOME/.config/matej-packages.txt  | tr "\n" " "); do
  sudo apt-get install -y $i
done

# Create a dir for vlc's plugin to work properly
mkdir ~/.cache/vlc



# Install krohnkite
sudo apt install -y node-typescript
git clone https://github.com/esjeon/krohnkite.git $HOME/tmp/krohnkite
cd $HOME/tmp/krohnkite
make install
cd $HOME
mkdir -p ~/.local/share/kservices5/
ln -s ~/.local/share/kwin/scripts/krohnkite/metadata.desktop ~/.local/share/kservices5/krohnkite.desktop
